# Generated by Django 4.2.16 on 2025-11-23 09:50

import config.utils
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('custom', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_no', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Nu Registo do Antigo Aluno/NRE')),
                ('name', models.CharField(max_length=120, verbose_name='Nome Completo')),
                ('sex', models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], max_length=10, verbose_name='Sexo')),
                ('dob', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('pob', models.CharField(blank=True, max_length=120, null=True, verbose_name='Naturalidade')),
                ('father_name', models.CharField(blank=True, max_length=120, null=True, verbose_name='Nome Do Pai')),
                ('mother_name', models.CharField(blank=True, max_length=120, null=True, verbose_name='Nome Da Mãe')),
                ('email', models.EmailField(blank=True, max_length=150, null=True, verbose_name='E-Mail')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Nu Telemovel')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=config.utils.alumni_photo, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif'])], verbose_name='Imagen')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('hashed', models.CharField(blank=True, max_length=32, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alumnicreatedbys', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alumnideletedbys', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alumniupdatetedbys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '01-Dadus_Alumni_Pessoal',
            },
        ),
        migrations.CreateModel(
            name='FurtherStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major', models.CharField(blank=True, max_length=255, null=True, verbose_name='Especialidade')),
                ('university', models.CharField(blank=True, max_length=255, null=True, verbose_name='Univesidade')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('hashed', models.CharField(blank=True, max_length=32, null=True)),
                ('alumni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='further_studies', to='alumni.alumni')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='custom.nasaun', verbose_name='País')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estudocreatedbys', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estudodeletedbys', to=settings.AUTH_USER_MODEL)),
                ('study_level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='custom.nivelmaster', verbose_name='Nivel Estudo')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estudoupdatetedbys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '05-Dadus_Alumni_Estudo',
            },
        ),
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_field', models.CharField(choices=[('Relevante', 'Relevante'), ('Não Relevante', 'Não Relevante')], max_length=50, verbose_name='Estado Servico')),
                ('institution', models.CharField(blank=True, max_length=150, null=True, verbose_name='instituticão')),
                ('department', models.CharField(blank=True, max_length=150, null=True, verbose_name='Departamento')),
                ('position', models.CharField(blank=True, max_length=150, null=True, verbose_name='Posicão')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('hashed', models.CharField(blank=True, max_length=32, null=True)),
                ('alumni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='careers', to='alumni.alumni')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='custom.nasaun', verbose_name='País')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Careiracreatedbys', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Careiradeletedbys', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Careiraupdatetedbys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '04-Dadus_Alumni_Careira',
            },
        ),
        migrations.CreateModel(
            name='AlumniUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('hashed', models.CharField(blank=True, max_length=32, null=True)),
                ('alumni', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account', to='alumni.alumni')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Alumnicreatedbys', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Alumnideletedbys', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Alumniupdatetedbys', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '06-Dadus_Alumni_user',
            },
        ),
        migrations.CreateModel(
            name='AlumniAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Detailho Endereso')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('hashed', models.CharField(blank=True, max_length=32, null=True)),
                ('ald', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='custom.subvillage', verbose_name='Aldeia')),
                ('alumni', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='alumni.alumni')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Addresscreatedbys', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Addressdeletedbys', to=settings.AUTH_USER_MODEL)),
                ('mun', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='custom.municipality', verbose_name='Município')),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='custom.administrativepost', verbose_name='Posto Administrativo')),
                ('suk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='custom.village', verbose_name='Suco')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Addressupdatetedbys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '02-Dadus_Alumni_Enderesu',
            },
        ),
        migrations.CreateModel(
            name='AcademicRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_start', models.CharField(blank=True, max_length=4, null=True, verbose_name='Ano Início')),
                ('thesis_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Titulo De Teze')),
                ('advisor_1', models.CharField(blank=True, max_length=120, null=True, verbose_name=' Oreintador I')),
                ('advisor_2', models.CharField(blank=True, max_length=120, null=True, verbose_name=' Oreintador II')),
                ('gpa', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='IPC')),
                ('predicate', models.CharField(blank=True, max_length=50, null=True, verbose_name='Predicado')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('hashed', models.CharField(blank=True, max_length=32, null=True)),
                ('alumni', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='academic', to='alumni.alumni')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Academiccreatedbys', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Academicdeletedbys', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='custom.departamento', verbose_name='Departamento')),
                ('faculty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='custom.faculdade', verbose_name='Faculdade')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Academicupdatetedbys', to=settings.AUTH_USER_MODEL)),
                ('year_graduation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='custom.year', verbose_name='Ano Termina')),
            ],
            options={
                'verbose_name_plural': '03-Dadus_Alumni_Academica',
            },
        ),
    ]
