# Generated by Django 4.2.16 on 2025-11-24 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0002_historicalfurtherstudy_historicalcareer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni',
            name='pos',
            field=models.CharField(blank=True, choices=[('Em Estudo', 'Em Estudo'), ('No Trabalho', 'No Trabalho'), ('Em Estudo e No Trabalho', 'Em Estudo e No Trabalho'), ('Outro', 'Outro')], default='Outro', max_length=50, null=True, verbose_name='Status Ataul'),
        ),
        migrations.AddField(
            model_name='historicalalumni',
            name='pos',
            field=models.CharField(blank=True, choices=[('Em Estudo', 'Em Estudo'), ('No Trabalho', 'No Trabalho'), ('Em Estudo e No Trabalho', 'Em Estudo e No Trabalho'), ('Outro', 'Outro')], default='Outro', max_length=50, null=True, verbose_name='Status Ataul'),
        ),
    ]
