# Generated by Django 4.2.16 on 2025-11-27 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0003_alumni_pos_historicalalumni_pos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumni',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='historicalalumni',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
