# Generated by Django 4.2.16 on 2025-11-29 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0002_alter_municipality_options'),
        ('alumni', '0004_alter_alumni_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumniuser',
            name='alumni',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account', to='alumni.alumni'),
        ),
        migrations.AlterField(
            model_name='furtherstudy',
            name='alumni',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='further_studies', to='alumni.alumni'),
        ),
        migrations.AlterField(
            model_name='furtherstudy',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='custom.nasaun', verbose_name='País'),
        ),
    ]
