# Generated by Django 4.2.16 on 2025-11-29 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0005_alter_alumniuser_alumni_alter_furtherstudy_alumni_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni',
            name='pos_outro',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Outro Descrição'),
        ),
        migrations.AddField(
            model_name='historicalalumni',
            name='pos_outro',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Outro Descrição'),
        ),
    ]
