# Generated by Django 4.2.16 on 2025-12-02 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0006_alumni_pos_outro_historicalalumni_pos_outro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumni',
            name='pos',
            field=models.CharField(blank=True, choices=[('Em Estudo', 'Em Estudo'), ('No Trabalho', 'No Trabalho'), ('Em Estudo e No Trabalho', 'Em Estudo e No Trabalho'), ('Outro', 'Outro')], max_length=50, null=True, verbose_name='Status Ataul'),
        ),
        migrations.AlterField(
            model_name='historicalalumni',
            name='pos',
            field=models.CharField(blank=True, choices=[('Em Estudo', 'Em Estudo'), ('No Trabalho', 'No Trabalho'), ('Em Estudo e No Trabalho', 'Em Estudo e No Trabalho'), ('Outro', 'Outro')], max_length=50, null=True, verbose_name='Status Ataul'),
        ),
    ]
