# Generated by Django 4.2.16 on 2025-11-23 09:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdministrativePost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Nome Postu')),
            ],
        ),
        migrations.CreateModel(
            name='CarouselSlide',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Títulu (h1)')),
                ('subtitle', models.TextField(blank=True, null=True, verbose_name='Deskrisaun (h4)')),
                ('image', models.ImageField(upload_to='carousel/', verbose_name='Imagem')),
                ('button_text', models.CharField(blank=True, max_length=100, null=True, verbose_name='Texto Botão')),
                ('button_link', models.URLField(blank=True, null=True, verbose_name='Link Botão')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem Slide')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativu')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(blank=True, max_length=30, null=True)),
                ('assunto', models.CharField(blank=True, max_length=150, null=True)),
                ('mensagem', models.TextField()),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Mensagem de Contato',
                'verbose_name_plural': 'Mensagens de Contato',
                'ordering': ['-data_envio'],
            },
        ),
        migrations.CreateModel(
            name='Faculdade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, verbose_name='Sigla')),
                ('name', models.CharField(max_length=50, verbose_name='Nome da Faculdade')),
            ],
        ),
        migrations.CreateModel(
            name='Informativo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Títulu')),
                ('image', models.ImageField(upload_to='informativo/', verbose_name='Imagem')),
                ('link', models.URLField(max_length=300, verbose_name='Link Artigu')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativu')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Informasaun',
                'verbose_name_plural': 'Informasaun',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, verbose_name='Sigla')),
                ('hckey', models.CharField(blank=True, max_length=25, null=True, verbose_name='Hckey')),
                ('name', models.CharField(max_length=50, verbose_name='Nome Municipio')),
            ],
        ),
        migrations.CreateModel(
            name='Nasaun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Naran Nasaun')),
            ],
        ),
        migrations.CreateModel(
            name='nivelmaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='Sigla')),
                ('name', models.CharField(max_length=50, verbose_name='Naran')),
            ],
        ),
        migrations.CreateModel(
            name='Pozisaun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Nome Pozisaun')),
            ],
        ),
        migrations.CreateModel(
            name='Relijiaun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Naran Relijiaun')),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Tinan')),
            ],
        ),
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Nome Sucu')),
                ('administrativePost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custom.administrativepost', verbose_name='Postu')),
            ],
        ),
        migrations.CreateModel(
            name='SubVillage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Nome Aldeia')),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custom.village', verbose_name='Suku')),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, verbose_name='Sigla')),
                ('name', models.CharField(max_length=100, verbose_name='Nome Do Departamento')),
                ('faculdade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custom.faculdade', verbose_name='Faculdades')),
            ],
        ),
        migrations.AddField(
            model_name='administrativepost',
            name='municipality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custom.municipality', verbose_name='Munisipiu'),
        ),
    ]
