# Generated by Django 4.2.16 on 2025-11-27 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='municipality',
            options={'ordering': ['name']},
        ),
    ]
