# Generated by Django 4.2.16 on 2025-12-02 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0002_alter_municipality_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faculdade',
            options={'ordering': ['name']},
        ),
    ]
